// <auto-generated />
namespace Agenda_de_ContatosMVC_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PersonFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonFix));
        
        string IMigrationMetadata.Id
        {
            get { return "202210122314392_PersonFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
